import { test, expect } from '@playwright/test'
import { openAccount, openCityPicker } from './navigation.mjs'

const events = Array.from({ length: 16 }, (_, index) => ({ id: `interaction-${index}`, title: `观察${index}生日`, date: `1990-${String(index % 12 + 1).padStart(2, '0')}-20`, type: 'birthday' }))

test.beforeEach(async ({ page }) => {
  await page.addInitScript(events => {
    localStorage.setItem('daygarden_guest_preferences_v1', JSON.stringify({ customEvents: events }))
    localStorage.setItem('daygarden_quick_notes_v1', JSON.stringify(Array.from({ length: 20 }, (_, index) => ({ id: `note-${index}`, content: `本地交互观察随想 ${index}`, createdAt: '2026-10-01T12:00:00Z' }))))
  }, events)
  await page.route('**/api/session', route => route.fulfill({ json: { user: null } }))
  await page.route('**/api/auth/providers', route => route.fulfill({ json: { google: false, github: false, dev: false } }))
  await page.route('https://api.open-meteo.com/**', route => route.fulfill({ json: { daily: { time: [] } } }))
  await page.goto('/')
})

async function eventModal(page) {
  await page.locator('.lazy-card', { hasText: '岁月里程' }).scrollIntoViewIfNeeded()
  await page.getByRole('button', { name: '管理重要日子与日程', exact: true }).click()
  return page.getByRole('dialog', { name: '岁月里程 · 重要日子与日程' })
}

async function expectInView(locator) {
  await expect.poll(() => locator.evaluate(element => {
    const r = element.getBoundingClientRect()
    const c = element.closest('.modal-content').getBoundingClientRect()
    return r.top >= c.top - 1 && r.bottom <= c.bottom + 1
  })).toBe(true)
}

test('New event panels stay visible and mode changes preserve drafts and explicit event types', async ({ page }) => {
  const modal = await eventModal(page)
  const form = modal.locator('.accordion-panel')
  const editor = modal.locator('.edit-card-panel')
  const pageScroll = await page.evaluate(() => scrollY)
  for (const position of [0, 0.5, 1]) {
    await modal.locator('.modal-content').evaluate((element, position) => { element.scrollTop = (element.scrollHeight - element.clientHeight) * position }, position)
    await modal.getByRole('button', { name: '添加日程、生日或纪念日', exact: true }).click()
    await expectInView(form)
    expect(await page.evaluate(() => scrollY)).toBe(pageScroll)
    await modal.getByRole('button', { name: '收起新增面板', exact: true }).click()
    await expect(form).toHaveCount(0)
  }
  await modal.getByRole('button', { name: '添加日程、生日或纪念日', exact: true }).click()
  const types = form.getByRole('group', { name: '事件类型' })
  await form.getByRole('button', { name: '确认添加', exact: true }).click()
  await expect(form.getByRole('alert')).toContainText('标题')
  await expect(form.getByLabel('名称（必填）', { exact: true })).toBeFocused()
  const typeBounds = await types.getByRole('button', { name: '🎂 生日', exact: true }).boundingBox()
  const calendarBounds = await form.getByRole('radio', { name: '公历', exact: true }).locator('..').boundingBox()
  expect(typeBounds.height).toBeGreaterThanOrEqual(40)
  expect(calendarBounds.height).toBeGreaterThanOrEqual(40)
  await types.getByRole('button', { name: '📅 日程计划', exact: true }).click()
  await form.getByLabel('名称（必填）', { exact: true }).fill('生日聚会安排')
  await expect(types.getByRole('button', { name: '📅 日程计划', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.press('Tab')
  await types.getByRole('button', { name: '📅 日程计划', exact: true }).focus()
  await page.keyboard.press('ArrowLeft')
  await expect(types.getByRole('button', { name: '💖 纪念日', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await types.getByRole('button', { name: '📅 日程计划', exact: true }).click()
  await form.getByLabel('截止／到期日期（公历）', { exact: true }).fill('2026-10-20')

  const card = modal.locator('[data-event-id="interaction-15"]')
  await card.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(form).toHaveCount(0)
  await expect(editor.getByRole('alert')).toHaveCount(0)
  await editor.getByLabel('名称（必填）', { exact: true }).fill('保留的编辑草稿')
  await modal.getByRole('button', { name: '添加日程、生日或纪念日', exact: true }).click()
  await expect(editor).toHaveCount(0)
  await expect(form.getByLabel('名称（必填）', { exact: true })).toHaveValue('生日聚会安排')
  await expect(types.getByRole('button', { name: '📅 日程计划', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await card.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(form).toHaveCount(0)
  await expect(editor.getByLabel('名称（必填）', { exact: true })).toHaveValue('保留的编辑草稿')
  await editor.getByRole('button', { name: '取消', exact: true }).click()
  await modal.getByRole('button', { name: '添加日程、生日或纪念日', exact: true }).click()
  await form.getByRole('button', { name: '确认添加', exact: true }).click()
  await expect(form).toHaveCount(0)
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('daygarden_guest_preferences_v1')).customEvents.find(event => event.title === '生日聚会安排'))
  expect(saved).toMatchObject({ type: 'schedule', isLunar: false, date: '2026-10-20' })
})

test('Validation stays with the edited card and saved cards are revealed even outside the old search', async ({ page }) => {
  const modal = await eventModal(page)
  await modal.locator('[data-event-id="interaction-15"]').getByRole('button', { name: '编辑', exact: true }).click()
  const editor = modal.locator('.edit-card-panel')
  const date = editor.getByLabel('出生日期（公历）', { exact: true })
  await date.fill('2026-02-30')
  await editor.getByRole('button', { name: '保存', exact: true }).click()
  await expect(editor.getByRole('alert')).toContainText('日期无效')
  await expect(date).toHaveAttribute('aria-invalid', 'true')
  await expect(date).toBeFocused()
  await expectInView(editor.getByRole('alert'))
  await editor.getByRole('button', { name: '取消', exact: true }).click()
  await modal.getByPlaceholder('搜索日程、纪念日、姓名或日期...').fill('观察0')
  await modal.locator('[data-event-id="interaction-0"]').getByRole('button', { name: '编辑', exact: true }).click()
  await expect(editor.getByRole('alert')).toHaveCount(0)
  await editor.getByLabel('名称（必填）', { exact: true }).fill('保存后可见的新名称')
  await editor.getByRole('button', { name: '保存', exact: true }).click()
  await expect(editor).toHaveCount(0)
  await expect(modal.getByPlaceholder('搜索日程、纪念日、姓名或日期...')).toHaveValue('')
  await expect(modal.locator('[data-event-id="interaction-0"]')).toContainText('保存后可见的新名称')
  await expectInView(modal.locator('[data-event-id="interaction-0"]'))
})

test('Mobile navigation keeps focus and scroll state consistent across menu, modal and breakpoint changes', async ({ page }) => {
  await page.setViewportSize({ width: 700, height: 900 })
  const menu = page.getByRole('button', { name: '展开导航菜单', exact: true })
  const drawer = page.getByRole('dialog', { name: '导航与功能菜单', exact: true })
  await menu.click()
  await expect(drawer.getByRole('button', { name: '关闭菜单', exact: true })).toBeFocused()
  expect(await page.evaluate(() => document.body.style.overflow)).toBe('hidden')
  await drawer.getByRole('button').last().focus()
  await page.keyboard.press('Tab')
  await expect(drawer.getByRole('button', { name: '关闭菜单', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(drawer.getByRole('button').last()).toBeFocused()
  await page.setViewportSize({ width: 750, height: 900 })
  await expect(menu).toBeVisible()
  await expect(drawer).toBeVisible()
  await page.setViewportSize({ width: 769, height: 900 })
  await expect(drawer).not.toBeVisible()
  await expect.poll(() => page.evaluate(() => document.body.style.overflow)).toBe('')
  await expect(page.getByRole('button', { name: '我的花园 · 账户与云端同步', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 750, height: 900 })
  await menu.click()
  await page.keyboard.press('Escape')
  await expect(drawer).not.toBeVisible()
  await expect(menu).toBeFocused()
  const city = await openCityPicker(page)
  expect(await page.evaluate(() => document.body.style.overflow)).toBe('hidden')
  await city.getByRole('button', { name: '关闭', exact: true }).click()
  await expect.poll(() => page.evaluate(() => document.body.style.overflow)).toBe('')
  await openAccount(page)
  const account = page.locator('.account-modal')
  await expect(account.getByRole('button', { name: '使用 Google 账户登录', exact: true })).toBeDisabled()
  await account.getByRole('button', { name: '邮箱与密码', exact: true }).focus()
  await page.keyboard.press('Tab')
  await expect(account.getByRole('button', { name: '关闭', exact: true })).toBeFocused()
})

test('New quick notes are revealed after expansion at the bottom of a long list', async ({ page }) => {
  await page.locator('.lazy-card', { hasText: '片刻随想' }).scrollIntoViewIfNeeded()
  await page.getByRole('button', { name: '全部随想', exact: true }).click()
  const modal = page.getByRole('dialog', { name: '片刻随笔 · 拾光心语' })
  await modal.locator('.modal-content').evaluate(element => { element.scrollTop = element.scrollHeight })
  await modal.getByRole('button', { name: '新增笔记', exact: true }).click()
  await expectInView(modal.locator('.accordion-panel'))
  await expect(modal.getByRole('textbox', { name: '新增随笔', exact: true })).toBeFocused()
})
